name: Deploy to Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Pull on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd a2rd_client
            ./scripts/deploy.sh
